### ISSUE TITLE
Polynomial regression core example error

### ISSUE THREAD

**Issue by droidresearch** [tensorflow/tfjs-examples#42]
Running the live example of polynomial regression core given in the github "https://storage.googleapis.com/tfjs-examples/dist/polynomial-regression-core/index.html"
throws the following error message

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>
No such object: tfjs-examples/dist/polynomial-regression-core/index.html
</Details>
</Error>`

**Comment by davidsoergel** [comment]
Confirmed, taking a look now

**Comment by davidsoergel** [comment]
Oh it's just a typo'd link.  The correct one is https://storage.googleapis.com/tfjs-examples/polynomial-regression-core/dist/index.html

**Comment by droidresearch** [comment]
Thank you it works.
