### ISSUE TITLE
Pac-Man demo should disable training until there are training images. Also better explain what to do.

### ISSUE THREAD

**Issue by kspviswa** [tensorflow/tfjs-examples#44]
I tried to clone `tfjs-examples`, installed `yarn` using `homebrew` and did `yarn build` & `yarn watch` to try the **pac-man** demo.

However when I attempt to **train**, I'm hit with below error in console.

![screen shot 2018-03-30 at 12 32 09 pm](https://user-images.githubusercontent.com/7476271/38151050-9259eda6-3416-11e8-81dc-36fcb01d06ea.png)

**Comment by tafsiri** [comment]
Hi @kspviswa could you give us a bit more system information? What version of crhome and what version of mac os?

Did recording of the samples otherwise work?

**Comment by kspviswa** [comment]
I'm using macOS sierra 10.12.5 . Chrome ver Version 65.0.3325.181 (Official Build) (64-bit).
4 GB RAM, 8 CPU.

Whenever hit **train** , am hit with error. What do you mean by "recording of the samples" ?

**Comment by davidsoergel** [comment]
Aha, perhaps the UI is not clear enough: before hitting train, you need to first record images of yourself looking up, down, left, and right (or pointing, etc.) by clicking in the squares next to each control button.  Holding the mouse button down collects multiple images.  We see good performance with ~40 each.  Those images are the training data; once they're collected, you can click "train".

**Comment by davidsoergel** [comment]
Confirmed if you click train without first collecting training images, you get the above error.

**Comment by kspviswa** [comment]
It is taking lot of time to record just 10 samples. Also I'm getting "unresponsive notification" while moving to next direction.

Why does recording takes lot of time? AFAIK it just samples input stream and store an image rite?

**Comment by nsthorat** [comment]
When you're actually recording we're passing it through MobileNet and storing the activation, which helps with the memory footprint as well as time to train.

What do you mean by moving to next direction?

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#59
