### ISSUE TITLE
A list of prereqs could be handy

### ISSUE THREAD

**Issue by sgserg** [tensorflow/tfjs-examples#49]
Examples work neither on OSX 10.9 (errors out on unsupported node version)
nor in iOS 11:

![beb1db23-6dcf-4596-b6cb-7a8966edc864](https://user-images.githubusercontent.com/5439847/38206449-2058728c-36b3-11e8-965c-f8b599a7fe50.jpeg)

**Comment by dsmilkov** [comment]
This issue was moved to tensorflow/tfjs#57
